# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import robot_pose_pb2 as robot__pose__pb2


class PoseStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetPose = channel.unary_unary(
                '/robot_pose.Pose/GetPose',
                request_serializer=robot__pose__pb2.GetPoseRequest.SerializeToString,
                response_deserializer=robot__pose__pb2.GetPoseReply.FromString,
                )


class PoseServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetPose(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PoseServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetPose': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPose,
                    request_deserializer=robot__pose__pb2.GetPoseRequest.FromString,
                    response_serializer=robot__pose__pb2.GetPoseReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'robot_pose.Pose', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Pose(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetPose(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/robot_pose.Pose/GetPose',
            robot__pose__pb2.GetPoseRequest.SerializeToString,
            robot__pose__pb2.GetPoseReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
