# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: robot_pose.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10robot_pose.proto\x12\nrobot_pose\"\x1d\n\nGetPoseAck\x12\x0f\n\x07success\x18\x01 \x01(\x08\"j\n\x0bGetPoseSend\x12\n\n\x02id\x18\x01 \x01(\t\x12\t\n\x01x\x18\x02 \x01(\x01\x12\t\n\x01y\x18\x03 \x01(\x01\x12\t\n\x01z\x18\x04 \x01(\x01\x12\n\n\x02qx\x18\x05 \x01(\x01\x12\n\n\x02qy\x18\x06 \x01(\x01\x12\n\n\x02qz\x18\x07 \x01(\x01\x12\n\n\x02qw\x18\x08 \x01(\x01\x32\x46\n\x08Position\x12:\n\x07GetPose\x12\x17.robot_pose.GetPoseSend\x1a\x16.robot_pose.GetPoseAckb\x06proto3')



_GETPOSEACK = DESCRIPTOR.message_types_by_name['GetPoseAck']
_GETPOSESEND = DESCRIPTOR.message_types_by_name['GetPoseSend']
GetPoseAck = _reflection.GeneratedProtocolMessageType('GetPoseAck', (_message.Message,), {
  'DESCRIPTOR' : _GETPOSEACK,
  '__module__' : 'robot_pose_pb2'
  # @@protoc_insertion_point(class_scope:robot_pose.GetPoseAck)
  })
_sym_db.RegisterMessage(GetPoseAck)

GetPoseSend = _reflection.GeneratedProtocolMessageType('GetPoseSend', (_message.Message,), {
  'DESCRIPTOR' : _GETPOSESEND,
  '__module__' : 'robot_pose_pb2'
  # @@protoc_insertion_point(class_scope:robot_pose.GetPoseSend)
  })
_sym_db.RegisterMessage(GetPoseSend)

_POSITION = DESCRIPTOR.services_by_name['Position']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GETPOSEACK._serialized_start=32
  _GETPOSEACK._serialized_end=61
  _GETPOSESEND._serialized_start=63
  _GETPOSESEND._serialized_end=169
  _POSITION._serialized_start=171
  _POSITION._serialized_end=241
# @@protoc_insertion_point(module_scope)
